CalculatorWEB/src/com/jdb/managedbeans/BasicCalcMB.java
package com.jdb.managedbeans;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.SQLException;
import java.util.Date;

import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.application.ResourceHandler;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import com.jdb.ejb.beans.interfaces.AuditLocal;
import com.jdb.jpa.entity.Audit;
import com.jdb.jpa.entity.User;
import com.jdb.utils.Operators;

@ViewScoped
@ManagedBean(name = "basic", eager = true)
public class BasicCalcMB {

	@EJB
	AuditLocal auditLocal;

	private Operators operator;
	private BigDecimal inputNumber1;
	private BigDecimal inputNumber2;
	private BigDecimal result;
	private int round = 2;

	public void calculate() {
		if (inputNumber1 == null) {
			addErrorMessage("Please enter a value for input 1");
			return;
		}
		if (inputNumber2 == null) {
			addErrorMessage("Please enter a value for input 2");
			return;
		}
		result = operator.calculate(inputNumber1, inputNumber2, round).setScale(round, RoundingMode.HALF_EVEN);
		Audit audit = new Audit();
		audit.setAnswer(result);
		audit.setCalculation(operator.getCalculation(inputNumber1, inputNumber2));
		audit.setRequestedDate(new java.sql.Timestamp(new Date().getTime()));
		audit.setUserName(getUserName());
		audit.setRounding(round);
		try {
			auditLocal.writeAudit(audit);
		} catch (SQLException se) {
			addErrorMessage("Failed to Write to Audit " + se.getMessage());
		}
	}

	private String getUserName() {
		FacesContext context = FacesContext.getCurrentInstance();
		User user = (User) context.getExternalContext().getSessionMap().get("user");
		System.out.println("user id = " + user.getId());
		return user.getUsername();
	}

	private void addErrorMessage(String message) {
		FacesContext context = FacesContext.getCurrentInstance();
		context.addMessage(null, new FacesMessage(message));
	}

	public Operators[] getOperators() {
		return Operators.values();
	}

	public BigDecimal getInputNumber1() {
		return inputNumber1;
	}

	public void setInputNumber1(BigDecimal inputNumber1) {
		this.inputNumber1 = inputNumber1;
	}

	public BigDecimal getInputNumber2() {
		return inputNumber2;
	}

	public void setInputNumber2(BigDecimal inputNumber2) {
		this.inputNumber2 = inputNumber2;
	}

	public BigDecimal getResult() {
		return result;
	}

	public void setResult(BigDecimal result) {
		this.result = result;
	}

	public Operators getOperator() {
		return operator;
	}

	public void setOperator(Operators operator) {
		this.operator = operator;
	}

	public int getRound() {
		return round;
	}

	public void setRound(int round) {
		this.round = round;
	}
}

CalculatorWEB/WebContent/advanceCalc.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="templates/navBar.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:c="http://java.sun.com/jsp/jstl/core">
	<ui:define name="page">Advance Calculator</ui:define>
	<ui:define name="content">
		<f:selectItems value="#{advance.Operators}" var="Operator"
			itemValue="#{Operator}" itemLabel="#{Operator.label}" />
		<h:form styleClass="form-horisontal">
			<div class="form-group">
				<h:outputLabel styleClass="control-lable col-sm-2"
					value="Input number 1" />
				<div class="col-sm-10">
					<h:inputText styleClass="form-control"
						value="#{advance.input}" />
				</div>
			</div>
			<div class="form-group">
				<h:outputLabel styleClass="control-lable col-sm-3"
					value="Places to Round" />
				<div class="col-sm-10">
					<h:selectOneMenu styleClass="control-lable col-sm-2"
						value="#{advance.round}">
						<f:selectItem itemValue="0" itemLabel="0" />
						<f:selectItem itemValue="1" itemLabel="1" />
						<f:selectItem itemValue="2" itemLabel="2" />
						<f:selectItem itemValue="3" itemLabel="3" />
						<f:selectItem itemValue="4" itemLabel="4" />
					</h:selectOneMenu>
				</div>
			</div>
			<h:message globalOnly="true" />
			<div class="form-group">
				<div class="col-sm-offset-2">
					<h:commandButton styleClass="btn btn-defualt"
						action="#{advance.calculate()}" value="Calculate" />
				</div>
			</div>
			<c:if test="#{not empty advance.result}">
				<h:outputLabel styleClass="control-lable col-sm-2" value="Results" />
				<div class="col-sm-10">
					<h:outputLabel styleClass="control-lable col-sm-2"
						value="#{advance.result}" />
				</div>
			</c:if>
		</h:form>
	</ui:define>
</ui:composition>

CalculatorWEB/WebContent/audit.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="templates/navBar.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">
	<ui:define name="page">Audit</ui:define>
	<ui:define name="content">
		<h:form>
			<div class="form-group">
				<h:outputLabel styleClass="control-lable col-sm-3" value="User" />
				<div class="col-sm-10">
					<h:selectOneMenu styleClass="control-lable col-sm-2"
						value="#{audit.user}">
						<f:selectItem itemValue="" itemLabel="" />
						<f:selectItems value="#{audit.getAuditUsers()}" var="userList"
							itemValue="#{userList}" itemLabel="#{userList}" />
					</h:selectOneMenu>
				</div>
			</div>
			<div class="form-group">
				<h:outputLabel value="Date From" styleClass="control-label col-sm-2" />
				<div class="col-sm-2">
					<h:inputText value="#{audit.dateFrom}"
						styleClass="form-control datepicker" />
				</div>
			</div>
			<div class="form-group">
				<h:outputLabel value="Date To" styleClass="control-label col-sm-2" />
				<div class="col-sm-2">
					<h:inputText value="#{audit.dateTo}"
						styleClass="form-control datepicker" />
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-2">
					<h:commandButton styleClass="btn btn-defualt"
						action="#{audit.getAuditFilter()}" value="Filter" />
				</div>
			</div>
		</h:form>
		<table class="table table-bordered table-striped">
			<thead>
				<tr>
					<th>User</th>
					<th>Calculation</th>
					<th>Answer</th>
					<th>Rounding used</th>
					<th>Date</th>
				</tr>
			</thead>
			<tbody>
				<ui:repeat var="aud" value="#{audit.audits}">
					<tr>
						<td>#{aud.userName}</td>
						<td>#{aud.calculation}</td>
						<td>#{audit.convertAnswer(aud.answer)}</td>
						<td>#{aud.rounding}</td>
						<td>#{aud.requestedDate}</td>
					</tr>
				</ui:repeat>
			</tbody>
		</table>

	</ui:define>
</ui:composition>

CalculatorWEB/WebContent/basicCalc.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="templates/navBar.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:c="http://java.sun.com/jsp/jstl/core">
	<ui:define name="page">Basic Calculator</ui:define>
	<ui:define name="content">
		<f:selectItems value="#{basic.Operators}" var="Operator"
			itemValue="#{Operator}" itemLabel="#{Operator.label}" />
		<h:form styleClass="form-horisontal">
			<div class="form-group">
				<h:outputLabel styleClass="control-lable col-sm-2"
					value="Input number 1" />
				<div class="col-sm-10">
					<h:inputText styleClass="form-control"
						value="#{basic.inputNumber1}" />
				</div>
			</div>
			<div class="form-group">
			<h:outputLabel styleClass="control-lable col-sm-3"
					value="Operator" />
				<div class="col-sm-10">
					<h:selectOneMenu styleClass="control-lable col-sm-2"
						value="#{basic.operator}">
						<f:selectItems value="#{basic.operators}" var="operator"
							itemValue="#{operator}" itemLabel="#{operator.label}" />
					</h:selectOneMenu>
				</div>
			</div>
			<div class="form-group">
				<h:outputLabel styleClass="control-lable col-sm-3"
					value="Input number 2" />
				<div class="col-sm-10">
					<h:inputText styleClass="form-control"
						value="#{basic.inputNumber2}" />
				</div>
			</div>
			<div class="form-group">
				<h:outputLabel styleClass="control-lable col-sm-3"
					value="Places to Round" />
				<div class="col-sm-10">
					<h:selectOneMenu styleClass="control-lable col-sm-2"
						value="#{basic.round}">
						<f:selectItem itemValue="0" itemLabel="0" />
						<f:selectItem itemValue="1" itemLabel="1" />
						<f:selectItem itemValue="2" itemLabel="2" />
						<f:selectItem itemValue="3" itemLabel="3" />
						<f:selectItem itemValue="4" itemLabel="4" />
					</h:selectOneMenu>
				</div>
			</div>
			<h:message globalOnly="true" />
			<div class="form-group">
				<div class="col-sm-offset-2">
					<h:commandButton styleClass="btn btn-defualt"
						action="#{basic.calculate()}" value="Calculate" />
				</div>
			</div>
			<c:if test="#{not empty basic.result}">
				<h:outputLabel styleClass="control-lable col-sm-2" value="Results" />
				<div class="col-sm-10">
					<h:outputLabel styleClass="control-lable col-sm-2"
						value="#{basic.result}" />
				</div>
			</c:if>
		</h:form>


	</ui:define>
</ui:composition>

CalculatorWEB/WebContent/expired.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">

<head>
<title>Session expired</title>
<meta http-equiv="refresh"
	content="0;url=#{request.contextPath}/index.xhtml" />
</head>
<body>
	<h1>Session expired</h1>
	<h3>You will be redirected to login page</h3>
	<p>
		<a href="#{request.contextPath}/index.xhtml">Click here if
			redirect didn't work or when you're impatient</a>.
	</p>
</body>
</html>

CalculatorWEB/WebContent/index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="templates/navBar.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:c="http://java.sun.com/jsp/jstl/core">
	<ui:define name="page">Calculator access</ui:define>
	<ui:define name="content">
		<h:form styleClass="form-horisontal">
			<div class="form-group">
				<h:outputLabel styleClass="control-lable col-sm-2" value="User Name" />
				<div class="col-sm-10">
					<h:inputText styleClass="form-control" value="#{access.userName}" />
				</div>
			</div>
			<div class="form-group">
				<h:outputLabel styleClass="control-lable col-sm-2" value="Password" />
				<div class="col-sm-10">
					<h:inputSecret styleClass="form-control" value="#{access.password}" />
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-2">
					<h:commandButton styleClass="btn btn-defualt"
						action="#{access.login()}" value="Login" />
					<h:commandButton styleClass="btn btn-defualt"
						action="#{access.forwardToRegister()}" value="Register" />
				</div>
			</div>
		</h:form>
	</ui:define>
</ui:composition>

CalculatorWEB/WebContent/registerUser.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="templates/navBar.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">
	<ui:define name="page">Calculator Register</ui:define>
	<ui:define name="content">
		<h:form styleClass="form-horisontal">
			<div class="form-group">
				<h:outputLabel styleClass="control-lable col-sm-2" value="User Name" />
				<div class="col-sm-10">
					<h:inputText styleClass="form-control" value="#{access.userName}" />
				</div>
			</div>
			<div class="form-group">
				<h:outputLabel styleClass="control-lable col-sm-2" value="Password" />
				<div class="col-sm-10">
					<h:inputSecret styleClass="form-control" value="#{access.password}" />
				</div>
			</div>
			<div class="form-group">
				<h:outputLabel styleClass="control-lable col-sm-2"
					value="Administrator" />
				<div class="col-sm-10">
					<h:selectBooleanCheckbox value="#{access.administrator}" />
				</div>
			</div>
			<h:message globalOnly="true"/>
			<div class="form-group">
				<div class="col-sm-offset-2">
					<h:commandButton styleClass="btn btn-defualt"
						action="#{access.registerUser()}" value="Register" />
				</div>
			</div>
		</h:form>
	</ui:define>
</ui:composition>